name: 'Package'
description: 'Package `ukp-tailscale`'

inputs:
  nfpm_file:
    required: true
    description: "Name of the NFPM file"

outputs:
  semver:
    description: "Semantic version"
    value: ${{ steps.package.outputs.SEMVER }}
  pkg_component:
    description: "Proget component"
    value: ${{ steps.package.outputs.PKG_COMPONENT }}
  pkg_feed:
    description: "Proget feed"
    value: ${{ steps.package.outputs.PKG_FEED }}

runs:
  using: "composite"
  steps:
    - name: Package
      shell: bash
      id: package
      run: |
        set -xe
        ts_version="$(${UKP_PACKAGE}/usr/sbin/tailscaled --version)"
        VERSION=$(echo -n "$ts_version" | head -n 1 | sed 's/^v//')
        VERSION="${VERSION}-${COMMITS}+$(git rev-parse --short=7 HEAD)"
        PKG_COMPONENT=
        PKG_VERSION=
        PKG_FEED=

        branch2version() {
          # bash-internal version that is likely safer and faster
          local I=
          local C=
          local VER_BRANCH=
          local VER_USER=

          for (( I=0; I<${#1}; I++ )); do
            C="${1:$I:1}"
            if [[ "${C}" =~ [0-9a-zA-Z] ]]; then
              # Keep lower-case version of allowed character
              VER_BRANCH+="${C,,}"
            elif [[ "${C}" = "/" ]] && [ -z ${VER_USER} ] ; then
              # First '/': save content as user name
              VER_USER="${VER_BRANCH}"
              VER_BRANCH=
            else
              # Replace with '+'
              VER_BRANCH+="+"
            fi
          done

          printf "%s\n" "${VER_USER}" # can be empty
          printf "%s\n" "${VER_BRANCH}"
        }

        if [[ "$GITHUB_REF" == 'refs/heads/prod-stable' ]]; then
          PKG_COMPONENT="stable"
          PKG_VERSION="5:${VERSION}-9stable"
          PKG_FEED="cloud"
        elif [[ "$GITHUB_REF" == "refs/heads/prod-preview" ]]; then
          PKG_COMPONENT="preview"
          PKG_VERSION="5:${VERSION}-7preview"
          PKG_FEED="cloud"
        elif [[ "$GITHUB_REF" == 'refs/heads/prod-staging' ]]; then
          PKG_COMPONENT="staging"
          PKG_VERSION="5:${VERSION}-2staging"
          PKG_FEED="cloud-staging"
        else
          mapfile -t BRCUSTOM < <( branch2version "$( printf '%s' "$GITHUB_REF" | cut -f1,2 --complement -d'/' )")
          if [ -n "${BRCUSTOM[0]}" ]; then
            PKG_COMPONENT="${BRCUSTOM[0]}"
            PKG_VERSION="5:${VERSION}-0dev+${BRCUSTOM[0]}+${BRCUSTOM[1]}"
          else
            # branch does not have a user name
            PKG_COMPONENT="devel"
            PKG_VERSION="5:${VERSION}-0dev+${BRCUSTOM[1]}"
          fi
          PKG_FEED="cloud-internal"
        fi

        PKG_DISTVER=""
        if   [ "${DISTRO}" = "trixie" ]; then
          PKG_DISTVER="+deb13"
        elif [ "${DISTRO}" = "bookworm" ]; then
          PKG_DISTVER="+deb12"
        elif [ "${DISTRO}" = "bullseye" ]; then
          PKG_DISTVER="+deb11"
        fi

        export SEMVER="${PKG_VERSION}${PKG_DISTVER}"
        mkdir -p /dist;
        nfpm package --config ${{inputs.nfpm_file}} --packager deb --target /dist;
        rename 's/:/_/g' /dist/*.deb

        # Save the SEMVER for later steps
        echo "SEMVER=${SEMVER}" >> "$GITHUB_OUTPUT"
        echo "PKG_COMPONENT=${PKG_COMPONENT}" >> $GITHUB_OUTPUT
        echo "PKG_FEED=${PKG_FEED}" >> $GITHUB_OUTPUT
