name: release bullseye

on:
  push:
    branches: [prod-staging, prod-stable, prod-preview]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: debian:bullseye
    env:
      GO_VERSION: stable
      PYTHONDONTWRITEBYTECODE: 1
      UKP_PACKAGE: /platform-tailscaled-install
    steps:
    - name: Install checkout dependencies
      run: |
        set -xe;
        apt-get update;
        apt-get install --no-install-recommends -y ca-certificates
        apt-get install --no-install-recommends -y git

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false

    - name: Install build & release dependencies
      uses: ./.github/actions/install_dependencies

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      id: build
      uses: ./.github/actions/build

    - name: Package
      id: package
      uses:  ./.github/actions/package
      with:
        nfpm_file: "nfpm.yaml.bullseye"
      env:
        COMMITS: ${{ steps.build.outputs.commits }}

    - name: Upload build artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: platform-tailscaled-latest
        path: /dist
        if-no-files-found: error
        retention-days: 1
        overwrite: true

    - name: Publish to APT repository
      uses: ./.github/actions/publish
      env:
        DISTRO: "bullseye"
        PKG_COMPONENT: ${{ steps.package.outputs.pkg_component }}
        PKG_FEED: ${{ steps.package.outputs.pkg_feed }}
        PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
