name: release bookworm

on:
  push:
    branches: [prod-staging, prod-stable, prod-preview]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: debian:bookworm
    env:
      GO_VERSION: stable
      PYTHONDONTWRITEBYTECODE: 1
      UKP_PACKAGE: /platform-tailscaled-install
    steps:
    - name: Install build & release dependencies
      uses: unikraft-cloud/tailscale/.github/actions/install_dependencies@prod-staging

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false

    - name: Build
      uses: unikraft-cloud/tailscale/.github/actions/build@prod-staging

    - name: Package
      id: package
      uses: unikraft-cloud/tailscale/.github/actions/package@prod-staging
      with:
        nfpm_file: "nfpm.yaml.bookworm"

    - name: Upload build artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: platform-tailscaled-latest
        path: /dist
        if-no-files-found: error
        retention-days: 1
        overwrite: true

    - name: Publish to Gemfury
      if: github.ref == 'refs/heads/prod-stable' || github.ref == 'refs/heads/prod-staging'
      shell: bash
      run: |
        set -xe
        if [[ "$GITHUB_REF" == *"prod-stable"* ]]; then
          FUSER="$FURY_USER_STABLE"
          FTOKEN="$FURY_TOKEN_STABLE"
        fi
        fury push "$(ls /dist/*.deb)" --quiet --account "$FUSER" --api-token "$FTOKEN"
      env:
        FURY_TOKEN_STABLE: ${{ secrets.FURY_TOKEN }}
        FURY_USER_STABLE: ${{ secrets.FURY_USER }}
        FUSER: ${{ secrets.FURY_USER_STAGING }}
        FTOKEN: ${{ secrets.FURY_TOKEN_STAGING }}
    
    - name: Publish to APT repository
      uses: unikraft-cloud/tailscale/.github/actions/publish@prod-staging
      env:
        DISTRO: "bookworm"
        PKG_COMPONENT: ${{ steps.package.outputs.pkg_component }}
        PKG_FEED: ${{ steps.package.outputs.pkg_feed }}
        PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
